### PR TITLE
Use th-orphans instead of th-lift and custom Ord instances

### PR DESCRIPTION
**Pull request by ddssff**

### CODE REVIEW

**Comment by ddssff** [comment]
Its worth noting that haskell-src-meta uses th-orphans, and instances being what they are you can't really mix th-orphans and th-lift.

**Comment by ddssff** [comment]
Oh wait, th-lift is a dependency of th-orphans.  Now I'm confused.

**Comment by goldfirere** [comment]
I think this is a move in the right direction, but the patch as submitted also removes a bunch of non-redundant instances: all the `Lift` instances for the `Dxxx` types.

**Comment by ddssff** [comment]
No wonder it compiled!

**Comment by ddssff** [comment]
Should I refactor this pull request?

**Comment by ddssff** [comment]
Yeah, it needs to be redone - it botches the 7.6.3 compatibility.

**Pull request closed without merging**
