### PR TITLE
Add Language.Haskell.TH.Desugar.Context

### PR DESCRIPTION
**Pull request by ddssff**
This adds functions testContext and testInstances, for testing whether
the instances returned by qReifyInstances match all the superclasses
and equality predicates mentioned in the instance context.

### CODE REVIEW

**Comment by ddssff** [comment]
I'm going to move this module into the application that currently uses it, and maybe later to a separate library.

**Comment by goldfirere** [comment]
Thanks for the update.

I'm sorry that I seem to have lost the thread here. If you'd still like your work in th-desugar, I'll can take a closer look at it all today or tomorrow. If you're happy to pull this out into your own library, that's fine too.

Once again, sorry to have just left this hanging!

**Comment by ddssff** [comment]
No problem - it is not really ready for prime time, its unification
algorithm is pretty incomplete.  I think for now it can live with the
application that uses it, and maybe into its own library at some point.
Its not really desugaring anyway.

On Tue, Jan 27, 2015 at 8:13 AM, Richard Eisenberg <notifications@github.com

**Comment by ddssff** [comment]
I'm going to turn this into a new package th-context.

**Pull request closed without merging**
